/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EdGraph.Tenant.Client.Client;
using EdGraph.Tenant.Client.Api;
// uncomment below to import models
//using EdGraph.Tenant.Client.Model;

namespace EdGraph.Tenant.Client.Test.Api
{
    /// <summary>
    ///  Class for testing UsersLicensesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UsersLicensesApiTests : IDisposable
    {
        private UsersLicensesApi instance;

        public UsersLicensesApiTests()
        {
            instance = new UsersLicensesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UsersLicensesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' UsersLicensesApi
            //Assert.IsType<UsersLicensesApi>(instance);
        }

        /// <summary>
        /// Test AssignLicenseTenantUser
        /// </summary>
        [Fact]
        public void AssignLicenseTenantUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string userId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //IdentityApiUserV1AssignLicenseRequest? identityApiUserV1AssignLicenseRequest = null;
            //instance.AssignLicenseTenantUser(tenantId, userId, apiVersion, xVersion, identityApiUserV1AssignLicenseRequest);
        }

        /// <summary>
        /// Test AssignLicenseTenantUserBulk
        /// </summary>
        [Fact]
        public void AssignLicenseTenantUserBulkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string userId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //IdentityApiUserV1AssignLicenseBulkRequest? identityApiUserV1AssignLicenseBulkRequest = null;
            //instance.AssignLicenseTenantUserBulk(tenantId, userId, apiVersion, xVersion, identityApiUserV1AssignLicenseBulkRequest);
        }

        /// <summary>
        /// Test GetAllTenantUserApplicationLicenses
        /// </summary>
        [Fact]
        public void GetAllTenantUserApplicationLicensesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string userId = null;
            //int? pageSize = null;
            //int? pageIndex = null;
            //string? orderBy = null;
            //string? filter = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetAllTenantUserApplicationLicenses(tenantId, userId, pageSize, pageIndex, orderBy, filter, apiVersion, xVersion);
            //Assert.IsType<EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserLicensePaginatedItemsViewModel>(response);
        }

        /// <summary>
        /// Test RevokeLicenseTenantUser
        /// </summary>
        [Fact]
        public void RevokeLicenseTenantUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string userId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //IdentityApiUserV1RevokeLicenseRequest? identityApiUserV1RevokeLicenseRequest = null;
            //instance.RevokeLicenseTenantUser(tenantId, userId, apiVersion, xVersion, identityApiUserV1RevokeLicenseRequest);
        }

        /// <summary>
        /// Test RevokeLicenseTenantUserBulk
        /// </summary>
        [Fact]
        public void RevokeLicenseTenantUserBulkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string userId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //IdentityApiUserV1RevokeLicenseBulkRequest? identityApiUserV1RevokeLicenseBulkRequest = null;
            //instance.RevokeLicenseTenantUserBulk(tenantId, userId, apiVersion, xVersion, identityApiUserV1RevokeLicenseBulkRequest);
        }
    }
}
