/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationApiApplicationV3ApplicationProfileResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationApiApplicationV3ApplicationProfileResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationApiApplicationV3ApplicationProfileResponse
        //private ApplicationApiApplicationV3ApplicationProfileResponse instance;

        public ApplicationApiApplicationV3ApplicationProfileResponseTests()
        {
            // TODO uncomment below to create an instance of ApplicationApiApplicationV3ApplicationProfileResponse
            //instance = new ApplicationApiApplicationV3ApplicationProfileResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationApiApplicationV3ApplicationProfileResponse
        /// </summary>
        [Fact]
        public void ApplicationApiApplicationV3ApplicationProfileResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationApiApplicationV3ApplicationProfileResponse
            //Assert.IsType<ApplicationApiApplicationV3ApplicationProfileResponse>(instance);
        }


        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }
        /// <summary>
        /// Test the property 'ApplicationType'
        /// </summary>
        [Fact]
        public void ApplicationTypeTest()
        {
            // TODO unit test for the property 'ApplicationType'
        }
        /// <summary>
        /// Test the property 'ApplicationName'
        /// </summary>
        [Fact]
        public void ApplicationNameTest()
        {
            // TODO unit test for the property 'ApplicationName'
        }
        /// <summary>
        /// Test the property 'ApplicationUri'
        /// </summary>
        [Fact]
        public void ApplicationUriTest()
        {
            // TODO unit test for the property 'ApplicationUri'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'TooltipText'
        /// </summary>
        [Fact]
        public void TooltipTextTest()
        {
            // TODO unit test for the property 'TooltipText'
        }
        /// <summary>
        /// Test the property 'ApplicationDescription'
        /// </summary>
        [Fact]
        public void ApplicationDescriptionTest()
        {
            // TODO unit test for the property 'ApplicationDescription'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Fact]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }
        /// <summary>
        /// Test the property 'ApplicationStatus'
        /// </summary>
        [Fact]
        public void ApplicationStatusTest()
        {
            // TODO unit test for the property 'ApplicationStatus'
        }
        /// <summary>
        /// Test the property 'OpenInNewWindow'
        /// </summary>
        [Fact]
        public void OpenInNewWindowTest()
        {
            // TODO unit test for the property 'OpenInNewWindow'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'CreatedDateTime'
        /// </summary>
        [Fact]
        public void CreatedDateTimeTest()
        {
            // TODO unit test for the property 'CreatedDateTime'
        }
        /// <summary>
        /// Test the property 'LastModifiedBy'
        /// </summary>
        [Fact]
        public void LastModifiedByTest()
        {
            // TODO unit test for the property 'LastModifiedBy'
        }
        /// <summary>
        /// Test the property 'LastModifiedDateTime'
        /// </summary>
        [Fact]
        public void LastModifiedDateTimeTest()
        {
            // TODO unit test for the property 'LastModifiedDateTime'
        }
        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'SubscriptionType'
        /// </summary>
        [Fact]
        public void SubscriptionTypeTest()
        {
            // TODO unit test for the property 'SubscriptionType'
        }

    }

}
