/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationApiApplicationV2ApplicationStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationApiApplicationV2ApplicationStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationApiApplicationV2ApplicationStatus
        //private ApplicationApiApplicationV2ApplicationStatus instance;

        public ApplicationApiApplicationV2ApplicationStatusTests()
        {
            // TODO uncomment below to create an instance of ApplicationApiApplicationV2ApplicationStatus
            //instance = new ApplicationApiApplicationV2ApplicationStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationApiApplicationV2ApplicationStatus
        /// </summary>
        [Fact]
        public void ApplicationApiApplicationV2ApplicationStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationApiApplicationV2ApplicationStatus
            //Assert.IsType<ApplicationApiApplicationV2ApplicationStatus>(instance);
        }



    }

}
