/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationApiApplicationV3ApplicationSubscriptionType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationApiApplicationV3ApplicationSubscriptionTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationApiApplicationV3ApplicationSubscriptionType
        //private ApplicationApiApplicationV3ApplicationSubscriptionType instance;

        public ApplicationApiApplicationV3ApplicationSubscriptionTypeTests()
        {
            // TODO uncomment below to create an instance of ApplicationApiApplicationV3ApplicationSubscriptionType
            //instance = new ApplicationApiApplicationV3ApplicationSubscriptionType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationApiApplicationV3ApplicationSubscriptionType
        /// </summary>
        [Fact]
        public void ApplicationApiApplicationV3ApplicationSubscriptionTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationApiApplicationV3ApplicationSubscriptionType
            //Assert.IsType<ApplicationApiApplicationV3ApplicationSubscriptionType>(instance);
        }



    }

}
