/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest
        //private EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest instance;

        public EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequestTests()
        {
            // TODO uncomment below to create an instance of EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest
            //instance = new EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest
        /// </summary>
        [Fact]
        public void EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest
            //Assert.IsType<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'TenantTypes'
        /// </summary>
        [Fact]
        public void TenantTypesTest()
        {
            // TODO unit test for the property 'TenantTypes'
        }

        /// <summary>
        /// Test the property 'OrganizationIdentifier'
        /// </summary>
        [Fact]
        public void OrganizationIdentifierTest()
        {
            // TODO unit test for the property 'OrganizationIdentifier'
        }

        /// <summary>
        /// Test the property 'OrganizationName'
        /// </summary>
        [Fact]
        public void OrganizationNameTest()
        {
            // TODO unit test for the property 'OrganizationName'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'IsDemo'
        /// </summary>
        [Fact]
        public void IsDemoTest()
        {
            // TODO unit test for the property 'IsDemo'
        }

        /// <summary>
        /// Test the property 'AdditionalSettings'
        /// </summary>
        [Fact]
        public void AdditionalSettingsTest()
        {
            // TODO unit test for the property 'AdditionalSettings'
        }

        /// <summary>
        /// Test the property 'IdentityProviders'
        /// </summary>
        [Fact]
        public void IdentityProvidersTest()
        {
            // TODO unit test for the property 'IdentityProviders'
        }

        /// <summary>
        /// Test the property 'TenantStatus'
        /// </summary>
        [Fact]
        public void TenantStatusTest()
        {
            // TODO unit test for the property 'TenantStatus'
        }

        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Fact]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }
    }
}
