/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesApplicationRole
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesApplicationRoleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesApplicationRole
        //private EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesApplicationRole instance;

        public EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesApplicationRoleTests()
        {
            // TODO uncomment below to create an instance of EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesApplicationRole
            //instance = new EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesApplicationRole();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesApplicationRole
        /// </summary>
        [Fact]
        public void EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesApplicationRoleInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesApplicationRole
            //Assert.IsType<EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesApplicationRole>(instance);
        }


        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'IsAssigned'
        /// </summary>
        [Fact]
        public void IsAssignedTest()
        {
            // TODO unit test for the property 'IsAssigned'
        }

    }

}
