/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantSetting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantSettingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantSetting
        //private EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantSetting instance;

        public EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantSettingTests()
        {
            // TODO uncomment below to create an instance of EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantSetting
            //instance = new EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantSetting();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantSetting
        /// </summary>
        [Fact]
        public void EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantSettingInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantSetting
            //Assert.IsType<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantSetting>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Fact]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }
    }
}
