/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1AssignLicenseRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1AssignLicenseRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1AssignLicenseRequest
        //private IdentityApiUserV1AssignLicenseRequest instance;

        public IdentityApiUserV1AssignLicenseRequestTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1AssignLicenseRequest
            //instance = new IdentityApiUserV1AssignLicenseRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1AssignLicenseRequest
        /// </summary>
        [Fact]
        public void IdentityApiUserV1AssignLicenseRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1AssignLicenseRequest
            //Assert.IsType<IdentityApiUserV1AssignLicenseRequest>(instance);
        }


        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'SubscriptionId'
        /// </summary>
        [Fact]
        public void SubscriptionIdTest()
        {
            // TODO unit test for the property 'SubscriptionId'
        }
        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }

    }

}
