/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1EducationOrganization
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1EducationOrganizationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1EducationOrganization
        //private IdentityApiUserV1EducationOrganization instance;

        public IdentityApiUserV1EducationOrganizationTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1EducationOrganization
            //instance = new IdentityApiUserV1EducationOrganization();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1EducationOrganization
        /// </summary>
        [Fact]
        public void IdentityApiUserV1EducationOrganizationInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1EducationOrganization
            //Assert.IsType<IdentityApiUserV1EducationOrganization>(instance);
        }

        /// <summary>
        /// Test the property 'EducationOrganizationId'
        /// </summary>
        [Fact]
        public void EducationOrganizationIdTest()
        {
            // TODO unit test for the property 'EducationOrganizationId'
        }

        /// <summary>
        /// Test the property 'EducationOrganizationName'
        /// </summary>
        [Fact]
        public void EducationOrganizationNameTest()
        {
            // TODO unit test for the property 'EducationOrganizationName'
        }

        /// <summary>
        /// Test the property 'StaffClassification'
        /// </summary>
        [Fact]
        public void StaffClassificationTest()
        {
            // TODO unit test for the property 'StaffClassification'
        }
    }
}
