/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiApiClientV1RegenerateApiClientSecretRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiApiClientV1RegenerateApiClientSecretRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiApiClientV1RegenerateApiClientSecretRequest
        //private IdentityApiApiClientV1RegenerateApiClientSecretRequest instance;

        public IdentityApiApiClientV1RegenerateApiClientSecretRequestTests()
        {
            // TODO uncomment below to create an instance of IdentityApiApiClientV1RegenerateApiClientSecretRequest
            //instance = new IdentityApiApiClientV1RegenerateApiClientSecretRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiApiClientV1RegenerateApiClientSecretRequest
        /// </summary>
        [Fact]
        public void IdentityApiApiClientV1RegenerateApiClientSecretRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiApiClientV1RegenerateApiClientSecretRequest
            //Assert.IsType<IdentityApiApiClientV1RegenerateApiClientSecretRequest>(instance);
        }


        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'SecretExpirationDateTime'
        /// </summary>
        [Fact]
        public void SecretExpirationDateTimeTest()
        {
            // TODO unit test for the property 'SecretExpirationDateTime'
        }

    }

}
