/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiStaffClassificationV1StaffClassificationUpdatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiStaffClassificationV1StaffClassificationUpdatedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiStaffClassificationV1StaffClassificationUpdatedResponse
        //private IdentityApiStaffClassificationV1StaffClassificationUpdatedResponse instance;

        public IdentityApiStaffClassificationV1StaffClassificationUpdatedResponseTests()
        {
            // TODO uncomment below to create an instance of IdentityApiStaffClassificationV1StaffClassificationUpdatedResponse
            //instance = new IdentityApiStaffClassificationV1StaffClassificationUpdatedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiStaffClassificationV1StaffClassificationUpdatedResponse
        /// </summary>
        [Fact]
        public void IdentityApiStaffClassificationV1StaffClassificationUpdatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiStaffClassificationV1StaffClassificationUpdatedResponse
            //Assert.IsType<IdentityApiStaffClassificationV1StaffClassificationUpdatedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
