/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiInvitationV1SendInvitationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiInvitationV1SendInvitationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiInvitationV1SendInvitationRequest
        //private IdentityApiInvitationV1SendInvitationRequest instance;

        public IdentityApiInvitationV1SendInvitationRequestTests()
        {
            // TODO uncomment below to create an instance of IdentityApiInvitationV1SendInvitationRequest
            //instance = new IdentityApiInvitationV1SendInvitationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiInvitationV1SendInvitationRequest
        /// </summary>
        [Fact]
        public void IdentityApiInvitationV1SendInvitationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiInvitationV1SendInvitationRequest
            //Assert.IsType<IdentityApiInvitationV1SendInvitationRequest>(instance);
        }


        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'AssignLicenseRequests'
        /// </summary>
        [Fact]
        public void AssignLicenseRequestsTest()
        {
            // TODO unit test for the property 'AssignLicenseRequests'
        }

    }

}
