/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1UpdateUserRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1UpdateUserRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1UpdateUserRequest
        //private IdentityApiUserV1UpdateUserRequest instance;

        public IdentityApiUserV1UpdateUserRequestTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1UpdateUserRequest
            //instance = new IdentityApiUserV1UpdateUserRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1UpdateUserRequest
        /// </summary>
        [Fact]
        public void IdentityApiUserV1UpdateUserRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1UpdateUserRequest
            //Assert.IsType<IdentityApiUserV1UpdateUserRequest>(instance);
        }


        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }

    }

}
