/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiInvitationV1InvitationSentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiInvitationV1InvitationSentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiInvitationV1InvitationSentResponse
        //private IdentityApiInvitationV1InvitationSentResponse instance;

        public IdentityApiInvitationV1InvitationSentResponseTests()
        {
            // TODO uncomment below to create an instance of IdentityApiInvitationV1InvitationSentResponse
            //instance = new IdentityApiInvitationV1InvitationSentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiInvitationV1InvitationSentResponse
        /// </summary>
        [Fact]
        public void IdentityApiInvitationV1InvitationSentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiInvitationV1InvitationSentResponse
            //Assert.IsType<IdentityApiInvitationV1InvitationSentResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'InvitationId'
        /// </summary>
        [Fact]
        public void InvitationIdTest()
        {
            // TODO unit test for the property 'InvitationId'
        }
    }
}
