/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiApiClientV1ApiClientPaginatedItemsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiApiClientV1ApiClientPaginatedItemsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiApiClientV1ApiClientPaginatedItemsResponse
        //private IdentityApiApiClientV1ApiClientPaginatedItemsResponse instance;

        public IdentityApiApiClientV1ApiClientPaginatedItemsResponseTests()
        {
            // TODO uncomment below to create an instance of IdentityApiApiClientV1ApiClientPaginatedItemsResponse
            //instance = new IdentityApiApiClientV1ApiClientPaginatedItemsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiApiClientV1ApiClientPaginatedItemsResponse
        /// </summary>
        [Fact]
        public void IdentityApiApiClientV1ApiClientPaginatedItemsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiApiClientV1ApiClientPaginatedItemsResponse
            //Assert.IsType<IdentityApiApiClientV1ApiClientPaginatedItemsResponse>(instance);
        }


        /// <summary>
        /// Test the property 'PageIndex'
        /// </summary>
        [Fact]
        public void PageIndexTest()
        {
            // TODO unit test for the property 'PageIndex'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
