/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TenantApiPartnershipV1PartnershipSyncDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TenantApiPartnershipV1PartnershipSyncDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TenantApiPartnershipV1PartnershipSyncDTO
        //private TenantApiPartnershipV1PartnershipSyncDTO instance;

        public TenantApiPartnershipV1PartnershipSyncDTOTests()
        {
            // TODO uncomment below to create an instance of TenantApiPartnershipV1PartnershipSyncDTO
            //instance = new TenantApiPartnershipV1PartnershipSyncDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TenantApiPartnershipV1PartnershipSyncDTO
        /// </summary>
        [Fact]
        public void TenantApiPartnershipV1PartnershipSyncDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" TenantApiPartnershipV1PartnershipSyncDTO
            //Assert.IsType<TenantApiPartnershipV1PartnershipSyncDTO>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
