/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TenantApiTenantV1InstanceDatabases
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TenantApiTenantV1InstanceDatabasesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TenantApiTenantV1InstanceDatabases
        //private TenantApiTenantV1InstanceDatabases instance;

        public TenantApiTenantV1InstanceDatabasesTests()
        {
            // TODO uncomment below to create an instance of TenantApiTenantV1InstanceDatabases
            //instance = new TenantApiTenantV1InstanceDatabases();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TenantApiTenantV1InstanceDatabases
        /// </summary>
        [Fact]
        public void TenantApiTenantV1InstanceDatabasesInstanceTest()
        {
            // TODO uncomment below to test "IsType" TenantApiTenantV1InstanceDatabases
            //Assert.IsType<TenantApiTenantV1InstanceDatabases>(instance);
        }

        /// <summary>
        /// Test the property 'Admin'
        /// </summary>
        [Fact]
        public void AdminTest()
        {
            // TODO unit test for the property 'Admin'
        }

        /// <summary>
        /// Test the property 'Security'
        /// </summary>
        [Fact]
        public void SecurityTest()
        {
            // TODO unit test for the property 'Security'
        }

        /// <summary>
        /// Test the property 'Ods'
        /// </summary>
        [Fact]
        public void OdsTest()
        {
            // TODO unit test for the property 'Ods'
        }
    }
}
