/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TenantApiTenantV1UpdateSubscriptionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TenantApiTenantV1UpdateSubscriptionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TenantApiTenantV1UpdateSubscriptionRequest
        //private TenantApiTenantV1UpdateSubscriptionRequest instance;

        public TenantApiTenantV1UpdateSubscriptionRequestTests()
        {
            // TODO uncomment below to create an instance of TenantApiTenantV1UpdateSubscriptionRequest
            //instance = new TenantApiTenantV1UpdateSubscriptionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TenantApiTenantV1UpdateSubscriptionRequest
        /// </summary>
        [Fact]
        public void TenantApiTenantV1UpdateSubscriptionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TenantApiTenantV1UpdateSubscriptionRequest
            //Assert.IsType<TenantApiTenantV1UpdateSubscriptionRequest>(instance);
        }


        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'SubscriptionId'
        /// </summary>
        [Fact]
        public void SubscriptionIdTest()
        {
            // TODO unit test for the property 'SubscriptionId'
        }
        /// <summary>
        /// Test the property 'StartDateTime'
        /// </summary>
        [Fact]
        public void StartDateTimeTest()
        {
            // TODO unit test for the property 'StartDateTime'
        }
        /// <summary>
        /// Test the property 'EndDateTime'
        /// </summary>
        [Fact]
        public void EndDateTimeTest()
        {
            // TODO unit test for the property 'EndDateTime'
        }
        /// <summary>
        /// Test the property 'GracePeriod'
        /// </summary>
        [Fact]
        public void GracePeriodTest()
        {
            // TODO unit test for the property 'GracePeriod'
        }
        /// <summary>
        /// Test the property 'NumberOfLicenses'
        /// </summary>
        [Fact]
        public void NumberOfLicensesTest()
        {
            // TODO unit test for the property 'NumberOfLicenses'
        }
        /// <summary>
        /// Test the property 'AssignedLicenses'
        /// </summary>
        [Fact]
        public void AssignedLicensesTest()
        {
            // TODO unit test for the property 'AssignedLicenses'
        }
        /// <summary>
        /// Test the property 'LicenseType'
        /// </summary>
        [Fact]
        public void LicenseTypeTest()
        {
            // TODO unit test for the property 'LicenseType'
        }
        /// <summary>
        /// Test the property 'AutoAssign'
        /// </summary>
        [Fact]
        public void AutoAssignTest()
        {
            // TODO unit test for the property 'AutoAssign'
        }

    }

}
