/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TenantApiTenantV1CreateOnboardingStepRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TenantApiTenantV1CreateOnboardingStepRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TenantApiTenantV1CreateOnboardingStepRequest
        //private TenantApiTenantV1CreateOnboardingStepRequest instance;

        public TenantApiTenantV1CreateOnboardingStepRequestTests()
        {
            // TODO uncomment below to create an instance of TenantApiTenantV1CreateOnboardingStepRequest
            //instance = new TenantApiTenantV1CreateOnboardingStepRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TenantApiTenantV1CreateOnboardingStepRequest
        /// </summary>
        [Fact]
        public void TenantApiTenantV1CreateOnboardingStepRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TenantApiTenantV1CreateOnboardingStepRequest
            //Assert.IsType<TenantApiTenantV1CreateOnboardingStepRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
