/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TenantApiPartnershipV1PartnershipSyncType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TenantApiPartnershipV1PartnershipSyncTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TenantApiPartnershipV1PartnershipSyncType
        //private TenantApiPartnershipV1PartnershipSyncType instance;

        public TenantApiPartnershipV1PartnershipSyncTypeTests()
        {
            // TODO uncomment below to create an instance of TenantApiPartnershipV1PartnershipSyncType
            //instance = new TenantApiPartnershipV1PartnershipSyncType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TenantApiPartnershipV1PartnershipSyncType
        /// </summary>
        [Fact]
        public void TenantApiPartnershipV1PartnershipSyncTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" TenantApiPartnershipV1PartnershipSyncType
            //Assert.IsType<TenantApiPartnershipV1PartnershipSyncType>(instance);
        }
    }
}
