/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TenantApiTenantV1InstanceOdsDatabase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TenantApiTenantV1InstanceOdsDatabaseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TenantApiTenantV1InstanceOdsDatabase
        //private TenantApiTenantV1InstanceOdsDatabase instance;

        public TenantApiTenantV1InstanceOdsDatabaseTests()
        {
            // TODO uncomment below to create an instance of TenantApiTenantV1InstanceOdsDatabase
            //instance = new TenantApiTenantV1InstanceOdsDatabase();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TenantApiTenantV1InstanceOdsDatabase
        /// </summary>
        [Fact]
        public void TenantApiTenantV1InstanceOdsDatabaseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TenantApiTenantV1InstanceOdsDatabase
            //Assert.IsType<TenantApiTenantV1InstanceOdsDatabase>(instance);
        }


        /// <summary>
        /// Test the property 'SelectedTierId'
        /// </summary>
        [Fact]
        public void SelectedTierIdTest()
        {
            // TODO unit test for the property 'SelectedTierId'
        }
        /// <summary>
        /// Test the property 'SelectedTierName'
        /// </summary>
        [Fact]
        public void SelectedTierNameTest()
        {
            // TODO unit test for the property 'SelectedTierName'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Jobs'
        /// </summary>
        [Fact]
        public void JobsTest()
        {
            // TODO unit test for the property 'Jobs'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'OdsBackupCode'
        /// </summary>
        [Fact]
        public void OdsBackupCodeTest()
        {
            // TODO unit test for the property 'OdsBackupCode'
        }
        /// <summary>
        /// Test the property 'OdsBackupDescription'
        /// </summary>
        [Fact]
        public void OdsBackupDescriptionTest()
        {
            // TODO unit test for the property 'OdsBackupDescription'
        }

    }

}
