/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TenantApiTenantV1SubscriptionUpdatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TenantApiTenantV1SubscriptionUpdatedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TenantApiTenantV1SubscriptionUpdatedResponse
        //private TenantApiTenantV1SubscriptionUpdatedResponse instance;

        public TenantApiTenantV1SubscriptionUpdatedResponseTests()
        {
            // TODO uncomment below to create an instance of TenantApiTenantV1SubscriptionUpdatedResponse
            //instance = new TenantApiTenantV1SubscriptionUpdatedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TenantApiTenantV1SubscriptionUpdatedResponse
        /// </summary>
        [Fact]
        public void TenantApiTenantV1SubscriptionUpdatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TenantApiTenantV1SubscriptionUpdatedResponse
            //Assert.IsType<TenantApiTenantV1SubscriptionUpdatedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'SubscriptionId'
        /// </summary>
        [Fact]
        public void SubscriptionIdTest()
        {
            // TODO unit test for the property 'SubscriptionId'
        }
    }
}
