/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TenantApiTenantV1SetAppSettingsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TenantApiTenantV1SetAppSettingsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TenantApiTenantV1SetAppSettingsRequest
        //private TenantApiTenantV1SetAppSettingsRequest instance;

        public TenantApiTenantV1SetAppSettingsRequestTests()
        {
            // TODO uncomment below to create an instance of TenantApiTenantV1SetAppSettingsRequest
            //instance = new TenantApiTenantV1SetAppSettingsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TenantApiTenantV1SetAppSettingsRequest
        /// </summary>
        [Fact]
        public void TenantApiTenantV1SetAppSettingsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TenantApiTenantV1SetAppSettingsRequest
            //Assert.IsType<TenantApiTenantV1SetAppSettingsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Fact]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }
    }
}
