/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TenantApiTenantV1CreateOrganizationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TenantApiTenantV1CreateOrganizationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TenantApiTenantV1CreateOrganizationRequest
        //private TenantApiTenantV1CreateOrganizationRequest instance;

        public TenantApiTenantV1CreateOrganizationRequestTests()
        {
            // TODO uncomment below to create an instance of TenantApiTenantV1CreateOrganizationRequest
            //instance = new TenantApiTenantV1CreateOrganizationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TenantApiTenantV1CreateOrganizationRequest
        /// </summary>
        [Fact]
        public void TenantApiTenantV1CreateOrganizationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TenantApiTenantV1CreateOrganizationRequest
            //Assert.IsType<TenantApiTenantV1CreateOrganizationRequest>(instance);
        }


        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'IdentifierType'
        /// </summary>
        [Fact]
        public void IdentifierTypeTest()
        {
            // TODO unit test for the property 'IdentifierType'
        }
        /// <summary>
        /// Test the property 'IdentifierValue'
        /// </summary>
        [Fact]
        public void IdentifierValueTest()
        {
            // TODO unit test for the property 'IdentifierValue'
        }
        /// <summary>
        /// Test the property 'Discriminator'
        /// </summary>
        [Fact]
        public void DiscriminatorTest()
        {
            // TODO unit test for the property 'Discriminator'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'IncludeInJwt'
        /// </summary>
        [Fact]
        public void IncludeInJwtTest()
        {
            // TODO unit test for the property 'IncludeInJwt'
        }

    }

}
