/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TenantApiTenantV1EdFiAdminInstance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TenantApiTenantV1EdFiAdminInstanceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TenantApiTenantV1EdFiAdminInstance
        //private TenantApiTenantV1EdFiAdminInstance instance;

        public TenantApiTenantV1EdFiAdminInstanceTests()
        {
            // TODO uncomment below to create an instance of TenantApiTenantV1EdFiAdminInstance
            //instance = new TenantApiTenantV1EdFiAdminInstance();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TenantApiTenantV1EdFiAdminInstance
        /// </summary>
        [Fact]
        public void TenantApiTenantV1EdFiAdminInstanceInstanceTest()
        {
            // TODO uncomment below to test "IsType" TenantApiTenantV1EdFiAdminInstance
            //Assert.IsType<TenantApiTenantV1EdFiAdminInstance>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'InstanceName'
        /// </summary>
        [Fact]
        public void InstanceNameTest()
        {
            // TODO unit test for the property 'InstanceName'
        }

        /// <summary>
        /// Test the property 'UseCustomId'
        /// </summary>
        [Fact]
        public void UseCustomIdTest()
        {
            // TODO unit test for the property 'UseCustomId'
        }

        /// <summary>
        /// Test the property 'CustomId'
        /// </summary>
        [Fact]
        public void CustomIdTest()
        {
            // TODO unit test for the property 'CustomId'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'ConnectionName'
        /// </summary>
        [Fact]
        public void ConnectionNameTest()
        {
            // TODO unit test for the property 'ConnectionName'
        }

        /// <summary>
        /// Test the property 'SelectedConnectionId'
        /// </summary>
        [Fact]
        public void SelectedConnectionIdTest()
        {
            // TODO unit test for the property 'SelectedConnectionId'
        }

        /// <summary>
        /// Test the property 'Databases'
        /// </summary>
        [Fact]
        public void DatabasesTest()
        {
            // TODO unit test for the property 'Databases'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'ApiClientKey'
        /// </summary>
        [Fact]
        public void ApiClientKeyTest()
        {
            // TODO unit test for the property 'ApiClientKey'
        }

        /// <summary>
        /// Test the property 'ApiClientSecret'
        /// </summary>
        [Fact]
        public void ApiClientSecretTest()
        {
            // TODO unit test for the property 'ApiClientSecret'
        }

        /// <summary>
        /// Test the property 'IsApiClientSecretSecured'
        /// </summary>
        [Fact]
        public void IsApiClientSecretSecuredTest()
        {
            // TODO unit test for the property 'IsApiClientSecretSecured'
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }

        /// <summary>
        /// Test the property 'CreatedDateTime'
        /// </summary>
        [Fact]
        public void CreatedDateTimeTest()
        {
            // TODO unit test for the property 'CreatedDateTime'
        }

        /// <summary>
        /// Test the property 'IsDeleted'
        /// </summary>
        [Fact]
        public void IsDeletedTest()
        {
            // TODO unit test for the property 'IsDeleted'
        }

        /// <summary>
        /// Test the property 'LastModifiedBy'
        /// </summary>
        [Fact]
        public void LastModifiedByTest()
        {
            // TODO unit test for the property 'LastModifiedBy'
        }

        /// <summary>
        /// Test the property 'LastModifiedDateTime'
        /// </summary>
        [Fact]
        public void LastModifiedDateTimeTest()
        {
            // TODO unit test for the property 'LastModifiedDateTime'
        }

        /// <summary>
        /// Test the property 'ApiAuthUrl'
        /// </summary>
        [Fact]
        public void ApiAuthUrlTest()
        {
            // TODO unit test for the property 'ApiAuthUrl'
        }

        /// <summary>
        /// Test the property 'ApiResourcesUrls'
        /// </summary>
        [Fact]
        public void ApiResourcesUrlsTest()
        {
            // TODO unit test for the property 'ApiResourcesUrls'
        }

        /// <summary>
        /// Test the property 'ApiCompositesUrls'
        /// </summary>
        [Fact]
        public void ApiCompositesUrlsTest()
        {
            // TODO unit test for the property 'ApiCompositesUrls'
        }
    }
}
