/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Tenant.Client.Model;
using EdGraph.Tenant.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Tenant.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TenantApiTenantV1IdentityProviderStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TenantApiTenantV1IdentityProviderStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TenantApiTenantV1IdentityProviderStatus
        //private TenantApiTenantV1IdentityProviderStatus instance;

        public TenantApiTenantV1IdentityProviderStatusTests()
        {
            // TODO uncomment below to create an instance of TenantApiTenantV1IdentityProviderStatus
            //instance = new TenantApiTenantV1IdentityProviderStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TenantApiTenantV1IdentityProviderStatus
        /// </summary>
        [Fact]
        public void TenantApiTenantV1IdentityProviderStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" TenantApiTenantV1IdentityProviderStatus
            //Assert.IsType<TenantApiTenantV1IdentityProviderStatus>(instance);
        }
    }
}
