/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdGraph.Tenant.Client.Client.OpenAPIDateConverter;

namespace EdGraph.Tenant.Client.Model
{
    /// <summary>
    /// Defines TenantApi.Tenant.V1.TenantType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TenantApiTenantV1TenantType
    {
        /// <summary>
        /// Enum Unknown for value: Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown,

        /// <summary>
        /// Enum Internal for value: Internal
        /// </summary>
        [EnumMember(Value = "Internal")]
        Internal,

        /// <summary>
        /// Enum State for value: State
        /// </summary>
        [EnumMember(Value = "State")]
        State,

        /// <summary>
        /// Enum Collaborative for value: Collaborative
        /// </summary>
        [EnumMember(Value = "Collaborative")]
        Collaborative,

        /// <summary>
        /// Enum District for value: District
        /// </summary>
        [EnumMember(Value = "District")]
        District,

        /// <summary>
        /// Enum Partner for value: Partner
        /// </summary>
        [EnumMember(Value = "Partner")]
        Partner,

        /// <summary>
        /// Enum Teacher for value: Teacher
        /// </summary>
        [EnumMember(Value = "Teacher")]
        Teacher,

        /// <summary>
        /// Enum Student for value: Student
        /// </summary>
        [EnumMember(Value = "Student")]
        Student
    }

}
